const {nanoid} = require('nanoid');

const data = [
  {"id": "identity", "username": "anniehallpapillon" },
  {"id": "identity", "username": "barleyowlneo" },
  {"id": "identity", "username": "baseballbee" },
  {"id": "identity", "username": "blackwidowbass" },
  {"id": "identity", "username": "bladerunnermineweb" },
  {"id": "identity", "username": "brightcurlingcream" },
  {"id": "identity", "username": "chinatownsoybeans" },
  {"id": "identity", "username": "cowpiehamcow" },
  {"id": "identity", "username": "ednamodebread" },
  {"id": "identity", "username": "enchantingfog" },
  {"id": "identity", "username": "erisspacexdragon" },
  {"id": "identity", "username": "giraffecake" },
  {"id": "identity", "username": "golfantapplepiefog" },
  {"id": "identity", "username": "grapefruitvoyager2" },
  {"id": "identity", "username": "hamflyryecake" },
  {"id": "identity", "username": "hippopotamuscygnus" },
  {"id": "identity", "username": "hippopotamuspluto" },
  {"id": "identity", "username": "jurassicpark" },
  {"id": "identity", "username": "lightningdrum" },
  {"id": "identity", "username": "milkrelishbird" },
  {"id": "identity", "username": "mirfencingnixsalt" },
  {"id": "identity", "username": "oldeuboibane" },
  {"id": "identity", "username": "oldeuboieggham" },
  {"id": "identity", "username": "optimusprime" },
  {"id": "identity", "username": "pancakesice" },
  {"id": "identity", "username": "papillonokra" },
  {"id": "identity", "username": "papillonvirga" },
  {"id": "identity", "username": "peassingrye" },
  {"id": "identity", "username": "platoonmoderntimes" },
  {"id": "identity", "username": "poolalivethething" },
  {"id": "identity", "username": "redgladiatorsquid" },
  {"id": "identity", "username": "rhinocerosstyxrye" },
  {"id": "identity", "username": "romanholidayoboe" },
  {"id": "identity", "username": "roosterthekid" },
  {"id": "identity", "username": "ryebirthdaycakeneo" },
  {"id": "identity", "username": "sculpordwarf" },
  {"id": "identity", "username": "sealpiesweetrolls" },
  {"id": "identity", "username": "sevensamurainixfly" },
  {"id": "identity", "username": "softdrinkbee" },
  {"id": "identity", "username": "softdrinkmelon" },
  {"id": "identity", "username": "sopranomarsryerice" },
  {"id": "identity", "username": "stalkersauce" },
  {"id": "identity", "username": "thegodfather" },
  {"id": "identity", "username": "theshiningsoda" },
  {"id": "identity", "username": "toadblackberrybass" },
  {"id": "identity", "username": "tomatoesjungle" },
  {"id": "identity", "username": "walrusryebear" },
  {"id": "identity", "username": "webneohorsemir" },
  {"id": "identity", "username": "windflatalgol" },
  {"id": "identity", "username": "yipmanblackeye" }
];

data.forEach((user) => user.id = nanoid());

console.log(JSON.stringify(data));
